nats-connection-string: "nats://backend:password@bike.dowhile.se:4222"
nats-enabled: true
test-nats: false
collision_detector-enabled: true
stale-position-time: 10
deltatime: 10 #Deltatime determines how far into to the future to project positions
loglevel: "DEBUG"
vehicle_type_a: "bus"
vehicle_type_b: "bicycle"
