figure()
subplot(311)
plot(y_dt)
title('dT_acc')
subplot(312)
plot(y_acc)
legend('East', 'North', 'Up') 
title('Rotated and low passed filtered')
subplot(313)
plot(s.ALLsens(s.ALLsens(:,1) == 1,3:5))
legend('X', 'Y', 'Z')
title('Original acc measurment')